version: '3.7'
services:
  wordpress:
    build:
      context: ./wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: ${dbsigma.cdsciuum4t92.us-west-2.rds.amazonaws.com}
      WORDPRESS_DB_USER: ${dbsigma}
      WORDPRESS_DB_PASSWORD: ${password123}
      WORDPRESS_DB_NAME: ${admin}
    volumes:
      - wordpress_data:/var/www/html

  mysql:
    build:
      context: ./mysql
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  wordpress_data:
  mysql_data:
